spring:
  application:
    name: neo4j-spring-boot
  data:
    neo4j:
      database: cricbuzz
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: password
logging:
  level:
    org:
      springframework:
        data:
          neo4j: DEBUG
